insert into bairro(nome) values('Alto Guarani');
insert into bairro(nome) values('Arroio Leão');
insert into bairro(nome) values('Chácara Três Fronteiras');
insert into bairro(nome) values('Conjunto Habitacional Fernanda');
insert into bairro(nome) values('Conjunto Habitacional Novo Mundo');
insert into bairro(nome) values('Conjunto Habitacional Sol de Maio');
insert into bairro(nome) values('Conjunto Residencial Dourados');
insert into bairro(nome) values('Conjunto Residencial Graúna');
insert into bairro(nome) values('Conjunto Residencial Tucuruí');
insert into bairro(nome) values('Gleba Guarani');
insert into bairro(nome) values('Imóvel Foz do Iguaçu');
insert into bairro(nome) values('Jardim Alvorada');
insert into bairro(nome) values('Jardim Bandeirantes');
insert into bairro(nome) values('Jardim Cedro');
insert into bairro(nome) values('Jardim Congonhas');
insert into bairro(nome) values('Jardim Ipanema');
insert into bairro(nome) values('Jardim Mônaco');
insert into bairro(nome) values('Jardim Porto Dourado');
insert into bairro(nome) values('Jardim Santa Rita');
insert into bairro(nome) values('Jardim Três Fronteiras');
insert into bairro(nome) values('Jardim Vale do Sol');
insert into bairro(nome) values('Jardim Vasco da Gama');
insert into bairro(nome) values('Loteamento Don Ricardo');
insert into bairro(nome) values('Loteamento Gleba Guarani');
insert into bairro(nome) values('Loteamento Jardim Colombelli');
insert into bairro(nome) values('Loteamento Jardim Imperial');
insert into bairro(nome) values('Loteamento Jardim Madre Tereza I');
insert into bairro(nome) values('Loteamento Jardim Madre Tereza II');
insert into bairro(nome) values('Loteamento Menger');
insert into bairro(nome) values('Loteamento Novo Mundo');
insert into bairro(nome) values('Loteamento Pilarzinho');
insert into bairro(nome) values('Loteamento Residencial Jacqueline');
insert into bairro(nome) values('Loteamento Residencial Lagoa Vermelha');
insert into bairro(nome) values('Loteamento São João');
insert into bairro(nome) values('Loteamento Três Lagoas');
insert into bairro(nome) values('Loteamento Witt');
insert into bairro(nome) values('Parque Residencial Lagoa Azul');
insert into bairro(nome) values('Parque Três Fronteiras');
insert into bairro(nome) values('Vila Guarani');
insert into bairro(nome) values('Vila Miranda');
insert into bairro(nome) values('Vila Tibagi');
insert into bairro(nome) values('Vila C Nova');
insert into bairro(nome) values('Vila C Velha');
insert into bairro(nome) values('Jardim Almada');
insert into bairro(nome) values('Ilha Acaray');
insert into bairro(nome) values('Imóvel Gleba Bela Vista');
insert into bairro(nome) values('Loteamento Bela Vista II');
insert into bairro(nome) values('Loteamento Bela Vista de Itaipu - Parte I');
insert into bairro(nome) values('Loteamento Budel');
insert into bairro(nome) values('Jardim Califórnia');
insert into bairro(nome) values('Cidade Nova I');
insert into bairro(nome) values('Cidade Nova II');
insert into bairro(nome) values('Loteamento Jardim Curitiba');
insert into bairro(nome) values('Jardim Evangélico');
insert into bairro(nome) values('Jardim Florença');
insert into bairro(nome) values('Jardim Irma');
insert into bairro(nome) values('Jardim Itá');
insert into bairro(nome) values('Jardim Itaipu');
insert into bairro(nome) values('Jardim Marisa');
insert into bairro(nome) values('Jardim Nova Califórnia');
insert into bairro(nome) values('Jardim Olívia');
insert into bairro(nome) values('Jardim Princesa Diana');
insert into bairro(nome) values('Parque Linear');
insert into bairro(nome) values('Pólo Universitário');
insert into bairro(nome) values('Porto Belo');
insert into bairro(nome) values('Jardim Rose Magalhães');
insert into bairro(nome) values('Parque Industrial e Comercial São Paulo');
insert into bairro(nome) values('Loteamento São Roque');
insert into bairro(nome) values('Vila São Sebastião');
insert into bairro(nome) values('Jardim Universitário das Américas I');
insert into bairro(nome) values('Jardim Universitário das Américas II');
insert into bairro(nome) values('Jardim Veneza');
insert into bairro(nome) values('Vila Rural');
insert into bairro(nome) values('Mutirão 1º de Maio');
insert into bairro(nome) values('Imóvel M Boicy');
insert into bairro(nome) values('Jardim Copacabana II');
insert into bairro(nome) values('Jardim Europa');
insert into bairro(nome) values('Jardim Liberdade I');
insert into bairro(nome) values('Jardim Pacaembu');
insert into bairro(nome) values('Jardim San Rafael I');
insert into bairro(nome) values('Jardim San Rafael II');
insert into bairro(nome) values('Jardim São Miguel');
insert into bairro(nome) values('Jardim Soledade I');
insert into bairro(nome) values('Jardim Soledade II');
insert into bairro(nome) values('Jardim Tarobá II');
insert into bairro(nome) values('Jardim Terra e Lar');
insert into bairro(nome) values('Loteamento Residencial Itália');
insert into bairro(nome) values('Loteamento Jardim Residencial Caiobá');
insert into bairro(nome) values('Loteamento Rincão São Francisco');
insert into bairro(nome) values('Parque Residencial Morumbi I');
insert into bairro(nome) values('Parque Residencial Morumbi II');
insert into bairro(nome) values('Parque Residencial Morumbi III');
insert into bairro(nome) values('Parque Residencial Morumbi IV');
insert into bairro(nome) values('Parque Residencial Santa Rita');
insert into bairro(nome) values('Portal da Foz');
insert into bairro(nome) values('Vila Borges');
insert into bairro(nome) values('Vila das Batalhas');
insert into bairro(nome) values('Vila Independente');
insert into bairro(nome) values('Condomínio Horizontal Fechado Quinta do Sol');
insert into bairro(nome) values('Condomínio Lazer Helena');
insert into bairro(nome) values('Condomínio Residencial Fechado Solar das Crisálidas');
insert into bairro(nome) values('Conjunto Remador');
insert into bairro(nome) values('Conjunto Residencial Aristides Merhy (Profilurb I)');
insert into bairro(nome) values('Conjunto Residencial Piracema (Profilurb II)');
insert into bairro(nome) values('Jardim Ana Rouver');
insert into bairro(nome) values('Jardim Boa Esperança');
insert into bairro(nome) values('Jardim Cecília');
insert into bairro(nome) values('Jardim das Flores');
insert into bairro(nome) values('Jardim Elisa I');
insert into bairro(nome) values('Jardim Elisa II');
insert into bairro(nome) values('Jardim Guaíra');
insert into bairro(nome) values('Jardim do Horto');
insert into bairro(nome) values('Jardim Iara');
insert into bairro(nome) values('Jardim Morenitas I');
insert into bairro(nome) values('Jardim Morenitas II');
insert into bairro(nome) values('Jardim Oriente');
insert into bairro(nome) values('Jardim Polônia');
insert into bairro(nome) values('Jardim Residencial Deville');
insert into bairro(nome) values('Jardim Santa Cecília II');
insert into bairro(nome) values('Jardim Tropical');
insert into bairro(nome) values('Jardim Veraneio');
insert into bairro(nome) values('Loteamento Bourbon');
insert into bairro(nome) values('Loteamento Nossa Senhora da Luz');
insert into bairro(nome) values('Loteamento Parque das Três Fronteiras');
insert into bairro(nome) values('Parque Residencial Ouro Verde');
insert into bairro(nome) values('Parque do Patriarca');
insert into bairro(nome) values('Sohab');
insert into bairro(nome) values('Vila Adriana I');
insert into bairro(nome) values('Vila Adriana II');
insert into bairro(nome) values('Vila Padre Monti');
insert into bairro(nome) values('Vila Shalom');
insert into bairro(nome) values('Chácaras Dom Emílio');
insert into bairro(nome) values('Cognópolis');
insert into bairro(nome) values('Condomínio Residencial Fechado Village Iguaçu');
insert into bairro(nome) values('Jardim Copacabana I');
insert into bairro(nome) values('Jardim Dom Miguel Osman');
insert into bairro(nome) values('Jardim Dom Pedro I');
insert into bairro(nome) values('Jardim Dona Fátima Osman');
insert into bairro(nome) values('Jardim Dona Leila');
insert into bairro(nome) values('Jardim Estela');
insert into bairro(nome) values('Jardim Niterói I');
insert into bairro(nome) values('Jardim Niterói II');
insert into bairro(nome) values('Jardim Panorama I');
insert into bairro(nome) values('Jardim Panorama II');
insert into bairro(nome) values('Jardim Primavera');
insert into bairro(nome) values('Jardim Residencial Bela Vista');
insert into bairro(nome) values('Jardim Residencial São Roque I');
insert into bairro(nome) values('Jardim Residencial São Roque II');
insert into bairro(nome) values('Jardim São Bento');
insert into bairro(nome) values('Jardim São Luiz');
insert into bairro(nome) values('Jardim São Paulo I');
insert into bairro(nome) values('Jardim São Paulo II');
insert into bairro(nome) values('Jardim Residencial São Roque III');
insert into bairro(nome) values('Jardim Três Pinheiros');
insert into bairro(nome) values('Jardim Vitória');
insert into bairro(nome) values('Linha Guarapuava');
insert into bairro(nome) values('Loteamento Lindóia');
insert into bairro(nome) values('Loteamento Residencial Cohiguaçu');
insert into bairro(nome) values('Loteamento Residencial Iguaçu');
insert into bairro(nome) values('Condomínio Horizontal Fechado Maria Tereza');
insert into bairro(nome) values('Condomínio Horizontal Fechado Moradas do Parque');
insert into bairro(nome) values('Imóvel Madeireira');
insert into bairro(nome) values('Imóvel Nardina Duso');
insert into bairro(nome) values('Imóvel Olaria Fulgêncio');
insert into bairro(nome) values('Imóvel Portes');
insert into bairro(nome) values('Imóvel Porto Alegre');
insert into bairro(nome) values('Imóvel Rodrigues "A"');
insert into bairro(nome) values('Imóvel Santo Inácio');
insert into bairro(nome) values('Jardim América');
insert into bairro(nome) values('Jardim Boa Vista');
insert into bairro(nome) values('Jardim Central');
insert into bairro(nome) values('Jardim Cristina');
insert into bairro(nome) values('Jardim das Nações');
insert into bairro(nome) values('Jardim Jupira');
insert into bairro(nome) values('Loteamento Paraguaçu');
insert into bairro(nome) values('Loteamento Renato Festugato');
insert into bairro(nome) values('Parque Monjolo');
insert into bairro(nome) values('Vila Brasília');
insert into bairro(nome) values('Vila Paraguaia');
insert into bairro(nome) values('Vila Pérola');
insert into bairro(nome) values('Vila Portes');
insert into bairro(nome) values('Condomínio Arco di Roma');
insert into bairro(nome) values('Conjunto Habitacional Fechado Lago dos Cisnes');
insert into bairro(nome) values('Conjunto Habitacional Parque Imperatriz');
insert into bairro(nome) values('Conjunto Habitacional Plaza');
insert into bairro(nome) values('Distrito Industrial');
insert into bairro(nome) values('Jardim Ana Cristina');
insert into bairro(nome) values('Jardim Aurora');
insert into bairro(nome) values('Jardim Canadá I');
insert into bairro(nome) values('Jardim Canadá II');
insert into bairro(nome) values('Jardim das Palmeiras I');
insert into bairro(nome) values('Jardim das Palmeiras II');
insert into bairro(nome) values('Jardim Dona Rocca');
insert into bairro(nome) values('Jardim Duarte');
insert into bairro(nome) values('Jardim Lancaster I');
insert into bairro(nome) values('Jardim Lancaster III');
insert into bairro(nome) values('Jardim Lancaster IV');
insert into bairro(nome) values('Jardim Lancaster V');
insert into bairro(nome) values('Jardim Nacional');
insert into bairro(nome) values('Parque Imperatriz');
insert into bairro(nome) values('Parque Presidente II');
insert into bairro(nome) values('Parque Residencial Três Bandeiras');
insert into bairro(nome) values('Pilar Parque Campestre');
insert into bairro(nome) values('Vila Braz');
insert into bairro(nome) values('Vila Santo Antônio');
insert into bairro(nome) values('Condomínio Horizontal Fechado Porto Seguro');
insert into bairro(nome) values('Conjunto Belvedere I');
insert into bairro(nome) values('Loteamento Belvedere I');
insert into bairro(nome) values('Conjunto Residencial Aporã');
insert into bairro(nome) values('Jardim das Laranjeiras');
insert into bairro(nome) values('Jardim Bárbara');
insert into bairro(nome) values('Jardim Curitibano I');
insert into bairro(nome) values('Jardim Curitibano II');
insert into bairro(nome) values('Jardim Curitibano III');
insert into bairro(nome) values('Jardim Curitibano IV');
insert into bairro(nome) values('Jardim Estrela');
insert into bairro(nome) values('Jardim Ipê I');
insert into bairro(nome) values('Jardim Ipê II');
insert into bairro(nome) values('Jardim Ipê III');
insert into bairro(nome) values('Jardim Jasmim');
insert into bairro(nome) values('Jardim Lancaster II');
insert into bairro(nome) values('Jardim Norma');
insert into bairro(nome) values('Jardim Paraná');
insert into bairro(nome) values('Jardim Petrópolis');
insert into bairro(nome) values('Jardim Santa Rosa');
insert into bairro(nome) values('Parque Residencial Karla');
insert into bairro(nome) values('Vila A');
insert into bairro(nome) values('Vila B');
insert into bairro(nome) values('Centro');
insert into bairro(nome) values('Vila Maracanã');
insert into bairro(nome) values('Vila Itajubá');
insert into bairro(nome) values('Vila Remígio');
insert into bairro(nome) values('Jardim Los Angeles');
insert into bairro(nome) values('Condomínio Horizontal Fechado Residencial Central Park');
insert into bairro(nome) values('Condomínio Horizontal Country Iguaçu');
insert into bairro(nome) values('Jardim Eldorado');
insert into bairro(nome) values('Jardim Esmeralda I');
insert into bairro(nome) values('Jardim Esmeralda II');
insert into bairro(nome) values('Jardim Guarapuava I');
insert into bairro(nome) values('Jardim Guarapuava II');
insert into bairro(nome) values('Jardim Iguaçu');
insert into bairro(nome) values('Jardim Naipi');
insert into bairro(nome) values('Jardim Social I');
insert into bairro(nome) values('Jardim Social II');
insert into bairro(nome) values('Jardim Tarobá');
insert into bairro(nome) values('Loteamento Roth');
insert into bairro(nome) values('Loteamento Parque M Boicy');
insert into bairro(nome) values('Vila Bom Jesus');
insert into bairro(nome) values('Vila Matilde');
insert into bairro(nome) values('Vila Yolanda');
insert into bairro(nome) values('Alto São Francisco');
insert into bairro(nome) values('Beverly Falls Park');
insert into bairro(nome) values('Campos do Iguaçu I');
insert into bairro(nome) values('Campos do Iguaçu II');
insert into bairro(nome) values('Condomínio Fechado Residencial Castel Franco');
insert into bairro(nome) values('Condomínio Horizontal Fechado Izadora Parque');
insert into bairro(nome) values('Conjunto Libra I');
insert into bairro(nome) values('Conjunto Libra II');
insert into bairro(nome) values('Conjunto Libra III');
insert into bairro(nome) values('Conjunto Libra IV');
insert into bairro(nome) values('Flamboyant');
insert into bairro(nome) values('Imóvel Acaraizinho');
insert into bairro(nome) values('Imóvel Edmundo Weirich');
insert into bairro(nome) values('Imóvel Sotelo');
insert into bairro(nome) values('Jardim Acaray');
insert into bairro(nome) values('Jardim Alice I');
insert into bairro(nome) values('Jardim Alice II');
insert into bairro(nome) values('Jardim Amazonas');
insert into bairro(nome) values('Jardim Cappuccino');
insert into bairro(nome) values('Jardim Cláudia');
insert into bairro(nome) values('Jardim João Paulo II');
insert into bairro(nome) values('Jardim Langwinski');
insert into bairro(nome) values('Jardim Liberdade II');
insert into bairro(nome) values('Jardim Manaus');
insert into bairro(nome) values('Jardim Pólo Centro');
insert into bairro(nome) values('Jardim Residencial Itamaraty');
insert into bairro(nome) values('Loteamento Amauri Rainho');
insert into bairro(nome) values('Loteamento Rincão São Francisco (Cohapar III)');
insert into bairro(nome) values('Loteamento Santos Guglielmi');
insert into bairro(nome) values('Parque Presidente I');
insert into bairro(nome) values('Vila CR-1');
insert into bairro(nome) values('Vila Militar');
insert into bairro(nome) values('Condomínio Mata Verde');
insert into bairro(nome) values('Jardim Comercial e Residencial Cataratas');
insert into bairro(nome) values('Jardim Novo Horizonte');
insert into bairro(nome) values('Loteamento Darcy Werner');
insert into bairro(nome) values('Loteamento Dona Amanda');
insert into bairro(nome) values('Loteamento João Gonçalves Batista');
insert into bairro(nome) values('Parte Norte');
insert into bairro(nome) values('Parte Sul');
insert into bairro(nome) values('Vila Anita Garibaldi');
insert into bairro(nome) values('Vila Carimã');
insert into bairro(nome) values('Alto da Boa Vista');
insert into bairro(nome) values('Área Itaipu Binacional');
insert into bairro(nome) values('Gleba Passo Cuê');
insert into bairro(nome) values('Aeroporto');
insert into bairro(nome) values('Imóvel Alwin');
insert into bairro(nome) values('Vila Aparecidinha');
insert into bairro(nome) values('Arroio Dourado (Gleba II)');
insert into bairro(nome) values('Condomínio Residencial Campo dos Sonhos');
insert into bairro(nome) values('Condomínio Chácara Natureza');
insert into bairro(nome) values('Condomínio Residencial Serenologia');
insert into bairro(nome) values('Linha Keller');
insert into bairro(nome) values('Parque Nacional');
insert into bairro(nome) values('Imóvel Tamanduá');
insert into bairro(nome) values('Imóvel Tamanduazinho');
insert into bairro(nome) values('Remanso Grande (Gleba I)');
insert into bairro(nome) values('Sanga Funda');
insert into bairro(nome) values('Vila Bananal');